[App]
Name = "ai.h2o.wave.company_info_at_a_glance"
Version = "0.0.1"
Title = "Company information, powered by GenerativeAI"
Description = "Helping you leverage LLMs to do some quick research!"
Tags = ["GENERATIVE_AI", "DEMO", "INTERNAL", "DATA_SCIENCE"]
LongDescription = "LongDescription.md"
InstanceLifecycle = "MANAGED"

[Runtime]
Module = "src.app"
EnableOIDC = false
MemoryLimit = "16Gi"
MemoryReservation = "16Gi"

[[Env]]
Name= "LOGO"
Value = "https://h2o.ai/content/experience-fragments/h2o/us/en/site/header/master/_jcr_content/root/container/header_copy/logo.coreimg.svg/1696007565253/h2o-logo.svg"

[[Env]]
Name = "PRIMARY_COLOR"
Value = "#FEC925"

[[Env]]
Name = "SECONDARY_COLOR"
Value = "#E8E5E1"


[[Env]]
Name = "H2OGPTE_API_TOKEN"
Secret = "company-information-at-a-glance"
SecretKey = "h2ogpte-key"

[[Env]]
Name = "H2OGPTE_URL"
Secret = "grammar-syntax-and-review"
SecretKey = "h2ogpte-url"

[[Env]]
Name = "HEAP_ID"
Secret = "heap-analytics"
SecretKey = "id"
