[App]
Name = "wave-h2ogpt-audio-summarization"
Version = "0.0.6"
Title = "Audio Summarization"
Description = "Automatically transcribe, summarize, and analyze the sentiment of audio files"
Tags = ["GENERATIVE_AI", "OSS", "AI_FOR_LIFE"]
InstanceLifecycle = "MANAGED"
LongDescription = "LongDescription.md"

[Runtime]
Module = "app"
MemoryLimit = "16Gi"
MemoryReservation = "16Gi"
EnableOIDC = true

[[Env]]
Name = "H2OGPT_API_TOKEN"
Secret = "h2ogpt-oss"
SecretKey = "h2ogpt-key"


[[Env]]
Name = "H2OGPT_URL"
Secret = "h2ogpt-oss"
SecretKey = "h2ogpt-url"

[[Env]]
Name = "HEAP_ID"
Secret = "heap-analytics"
SecretKey = "id"
