[App]
Name = "ai.h2o.wave.tomatoAI"
Version = "0.0.1"
Title = "TomatoAI"
Description = "Grow Your Own Vegetables with the Power of GenAI."
Tags = ["GENERATIVE_AI", "DEMO", "INTERNAL", "DATA_SCIENCE"]
LongDescription = "LongDescription.md"
InstanceLifecycle = "MANAGED"

[Runtime]
Module = "src.app"
EnableOIDC = false
MemoryLimit = "16Gi"
MemoryReservation = "16Gi"

[H2OGPT]
H2OGPT_URL = "https://gpt.h2o.ai/"

[[Env]]
Name = "PRIMARY_COLOR"
Value = "#a32424"

[[Env]]
Name = "SECONDARY_COLOR"
Value = "#e2e2e2"

[[Env]]
Name = "H2OGPT_KEY"
Secret = "h2ogpt"
SecretKey = "h2ogpt-key"
Optional = true

[[Env]]
Name = "HEAP_ID"
Secret = "heap-analytics"
SecretKey = "id"