# ********RoostGPT********
"""
Test generated by RoostGPT for test python-unit-studypartner using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=landing_page_layout_a29b714ea2
ROOST_METHOD_SIG_HASH=landing_page_layout_3fc2cb5227

Scenario 1: Test the meta card information
Details:
  TestName: test_meta_card_info
  Description: This test is intended to verify that the meta card's title and icon are correctly set from the app's toml file.
Execution:
  Arrange: Initialize Q object with required app.toml values.
  Act: Invoke the landing_page_layout function with the Q object.
  Assert: Check that the title and icon of the meta card match the values set in the app.toml file.
Validation:
  This test is important to ensure the meta card's information is accurately retrieved from the app's toml file and correctly set in the function.

Scenario 2: Test the theme settings
Details:
  TestName: test_theme_settings
  Description: This test is intended to verify that the theme settings are correctly set with the default or environment variables.
Execution:
  Arrange: Set environment variables for PRIMARY_COLOR and SECONDARY_COLOR.
  Act: Invoke the landing_page_layout function with the Q object.
  Assert: Check that the theme settings match the set environment variables or default values.
Validation:
  This test ensures that the theme settings are correctly set, providing a consistent visual experience for the users.

Scenario 3: Test the script settings
Details:
  TestName: test_script_settings
  Description: This test is intended to verify that the script is correctly set with the heap_analytics function.
Execution:
  Arrange: Initialize Q object with required app.toml values.
  Act: Invoke the landing_page_layout function with the Q object.
  Assert: Check that the script is correctly set with the heap_analytics function.
Validation:
  This test ensures that the script is correctly set, providing accurate analytics and tracking for the application.

Scenario 4: Test the layout settings for different breakpoints
Details:
  TestName: test_layout_settings
  Description: This test is intended to verify that the layout settings are correctly set for different breakpoints.
Execution:
  Arrange: Initialize Q object with required app.toml values.
  Act: Invoke the landing_page_layout function with the Q object.
  Assert: Check that the layout settings for different breakpoints are correctly set.
Validation:
  This test ensures that the layout settings are correctly set for different breakpoints, providing an optimized viewing experience for users on different devices.
"""

# ********RoostGPT********
@pytest.mark.regression
def test_theme_settings(self):
    # Arrange
    os.environ['PRIMARY_COLOR'] = '#123456'
    os.environ['SECONDARY_COLOR'] = '#654321'
    q = Q()
    # Act
    landing_page_layout(q)
    # Assert
    assert q.page['meta'].themes[0].primary == '#123456'
    assert q.page['meta'].themes[0].card == '#ffffff'  # corrected from 'page' to 'card'
