# ********RoostGPT********
"""
Test generated by RoostGPT for test python-unit-studypartner using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=footer_card_062d99a4b9
ROOST_METHOD_SIG_HASH=footer_card_3e136a9ae6

```
Scenario 1: Validate the box value in the footer_card function
Details:
  TestName: test_footer_card_box_value
  Description: This test is intended to verify if the 'box' value of the footer card returned by the function is 'footer'.
Execution:
  Arrange: No arrangement necessary as no parameters are passed to the function.
  Act: Invoke the footer_card function and store the returned footer_card object.
  Assert: Check if the 'box' attribute of the returned footer_card object is equal to 'footer'.
Validation:
  Rationalize: The 'box' attribute is a crucial part of the footer_card function. It determines the placement of the footer card on the page. Thus, it's important to ensure the function sets this attribute correctly.

Scenario 2: Validate the caption value in the footer_card function
Details:
  TestName: test_footer_card_caption_value
  Description: This test is intended to verify if the 'caption' value of the footer card returned by the function is 'Made with 💛 and H2O Wave.'.
Execution:
  Arrange: No arrangement necessary as no parameters are passed to the function.
  Act: Invoke the footer_card function and store the returned footer_card object.
  Assert: Check if the 'caption' attribute of the returned footer_card object is equal to 'Made with 💛 and H2O Wave.'.
Validation:
  Rationalize: The 'caption' attribute provides a message to the user. It's important to ensure that the function sets this attribute correctly, as it can directly impact user understanding and experience.

Scenario 3: Test the footer_card function return type
Details:
  TestName: test_footer_card_return_type
  Description: This test is intended to verify if the footer_card function is returning an object of the correct type i.e., 'ui.footer_card'.
Execution:
  Arrange: No arrangement necessary as no parameters are passed to the function.
  Act: Invoke the footer_card function and store the returned footer_card object.
  Assert: Check if the returned object is of type 'ui.footer_card'.
Validation:
  Rationalize: Ensuring the return type of the function is important as it guarantees the function's compatibility with other parts of the code that use its output.
```
"""

# ********RoostGPT********
import pytest
from h2o_wave import ui
from cards import footer_card

class Test_CardsFooterCard:
    @pytest.mark.regression
    def test_footer_card_box_value(self):
        # Act
        fc = footer_card()
        # Assert
        assert fc.box == 'footer', 'Footer card box value does not match expected value "footer"'

    @pytest.mark.regression
    def test_footer_card_caption_value(self):
        # Act
        fc = footer_card()
        # Assert
        assert fc.caption == 'Made with 💛 and H2O Wave.', 'Footer card caption value does not match expected value "Made with 💛 and H2O Wave."'

    @pytest.mark.regression
    def test_footer_card_return_type(self):
        # Act
        fc = footer_card()
        # Assert
        assert isinstance(fc, ui.footer_card), 'Footer card object is not an instance of ui.footer_card'
