# ********RoostGPT********
"""
Test generated by RoostGPT for test python-unit-studypartner using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=footer_card_062d99a4b9
ROOST_METHOD_SIG_HASH=footer_card_3e136a9ae6

Scenario 1: Validating the Box Parameter in the Footer Card
Details:
  TestName: test_box_parameter
  Description: This test is intended to verify that the footer card's box parameter is correctly set to "footer".
Execution:
  Arrange: No setup required as the function does not take any parameters.
  Act: Invoke the function footer_card() without any parameters.
  Assert: Check that the returned footer_card's box property is set to "footer".
Validation:
  Rationale: Ensuring the box parameter is correctly set is crucial as this parameter determines where the card will be placed in the user interface.

Scenario 2: Validating the Caption Parameter in the Footer Card
Details:
  TestName: test_caption_parameter
  Description: This test is intended to verify that the footer card's caption parameter is correctly set to "Made with 💛 and H2O Wave."
Execution:
  Arrange: No setup required as the function does not take any parameters.
  Act: Invoke the function footer_card() without any parameters.
  Assert: Check that the returned footer_card's caption property is set to "Made with 💛 and H2O Wave."
Validation:
  Rationale: The caption parameter is crucial as it displays the message to the user. Ensuring it is correctly set is important for maintaining the user interface's integrity.

Scenario 3: Validating the Footer Card Type
Details:
  TestName: test_footer_card_type
  Description: This test is intended to verify that the returned object from the function footer_card() is of type ui.footer_card.
Execution:
  Arrange: No setup required as the function does not take any parameters.
  Act: Invoke the function footer_card() without any parameters.
  Assert: Check that the returned object is an instance of ui.footer_card.
Validation:
  Rationale: It is important to ensure that the function returns the correct type of object, which in this case should be a footer card. This ensures that the function is behaving as expected and can be used correctly in the user interface.
"""

# ********RoostGPT********
import os
from h2o_wave import ui, Q, data
from cards import footer_card
import pytest

class Test_CardsFooterCard:

    @pytest.mark.regression
    @pytest.mark.positive
    def test_box_parameter(self):
        result = footer_card()
        assert result.box == "footer", "Footer card box parameter is not set correctly."

    @pytest.mark.regression
    @pytest.mark.positive
    def test_caption_parameter(self):
        result = footer_card()
        assert result.caption == "Made with 💛 and H2O Wave.", "Footer card caption parameter is not set correctly."

    @pytest.mark.regression
    @pytest.mark.positive
    def test_footer_card_type(self):
        result = footer_card()
        assert isinstance(result, ui.footer_card), "Returned object is not of type ui.footer_card."
