[App]
Name = "ai.h2o.wave.weekly_meal_planning"
Version = "0.0.2"
Title = "Weekly Meal Planning"
Description = "Let AI cook up meal ideas for the whole family"
Tags = ["GENERATIVE_AI", "DEMO", "INTERNAL", "DATA_SCIENCE"]
LongDescription = "LongDescription.md"
InstanceLifecycle = "MANAGED"

[Runtime]
Module = "src.app"
EnableOIDC = false
MemoryLimit = "16Gi"
MemoryReservation = "16Gi"

[[Env]]
Name= "LOGO"
Value = "https://h2o.ai/content/experience-fragments/h2o/us/en/site/header/master/_jcr_content/root/container/header_copy/logo.coreimg.svg/1696007565253/h2o-logo.svg"

[[Env]]
Name = "THEME"
Value = "nature"


[[Env]]
Name = "H2OGPT_API_TOKEN"
Secret = "h2ogpt-oss"
SecretKey = "h2ogpt-key"

[[Env]]
Name = "H2OGPT_URL"
Secret = "h2ogpt-oss"
SecretKey = "h2ogpt-url"

[[Env]]
Name = "HEAP_ID"
Secret = "heap-analytics"
SecretKey = "id"
