[App]
Name = "ai.h2o.wave.template.chatbot"
Version = "0.0.4"
Title = "Chatbot Template"
Description = "H2O Wave Template for Chatbot Applications"
Tags = ["GENERATIVE_AI", "OSS"]
LongDescription = "LongDescription.md"

[Runtime]
Module = "app"
EnableOIDC = true

[[Env]]
Name = "H2OGPTE_URL"
Secret = "h2ogpte-shared"
SecretKey = "h2ogpte-url"
