[App]
Name = "ai.h2o.wave.make_home_listing"
Version = "0.0.1"
Title = "Make Your Own Home Listing"
Description = "Create listings for your home by customizing the home attributes and audience persona. "
Tags = ["GENERATIVE_AI", "DEMO", "INTERNAL", "DATA_SCIENCE"]
LongDescription = "LongDescription.md"
InstanceLifecycle = "MANAGED"

[Runtime]
Module = "src.app"
EnableOIDC = false
MemoryLimit = "16Gi"
MemoryReservation = "16Gi"

[[Env]]
Name= "LOGO"
Value = "https://h2o.ai/content/experience-fragments/h2o/us/en/site/header/master/_jcr_content/root/container/header_copy/logo.coreimg.svg/1696007565253/h2o-logo.svg"

[[Env]]
Name = "THEME"
Value = "winter-is-coming"


[[Env]]
Name = "H2OGPTE_API_TOKEN"
Secret = "h2ogpt-oss"
SecretKey = "h2ogpte-key"

[[Env]]
Name = "H2OGPTE_URL"
Secret = "h2ogpt-oss"
SecretKey = "h2ogpte-url"

[[Env]]
Name = "HEAP_ID"
Secret = "heap-analytics"
SecretKey = "id"
